/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt
 * to change this license Click
 * nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this
 * template
 */

import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class Demo extends javax.swing.JFrame {

  /**
   * Creates new form Demo
   */
  public Demo() { initComponents(); }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jSpinner1 = new javax.swing.JSpinner();
    buttonGroup1 = new javax.swing.ButtonGroup();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    lb_A = new javax.swing.JTextField();
    lb_b = new javax.swing.JTextField();
    lb_c = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    value_x1 = new javax.swing.JTextField();
    value_X2 = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    Giai = new javax.swing.JButton();
    ptn_Plus = new javax.swing.JRadioButton();
    ptn_Multiply = new javax.swing.JRadioButton();
    ptb_Subtract = new javax.swing.JRadioButton();
    ptn_Divide = new javax.swing.JRadioButton();
    txt_Result = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    Combo_Box = new javax.swing.JComboBox<>();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    lb_kitu = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setText("A");

    jLabel2.setText("B");

    jLabel3.setText("C");

    lb_A.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        lb_AActionPerformed(evt);
      }
    });

    lb_b.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        lb_bActionPerformed(evt);
      }
    });

    lb_c.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        lb_cActionPerformed(evt);
      }
    });

    jLabel4.setText("Nghiên X1");

    value_x1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        value_x1ActionPerformed(evt);
      }
    });

    jLabel5.setText("Nghiệm X2");

    jLabel6.setText("Nghiệm của phương trình");

    Giai.setText("Giai");
    Giai.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        GiaiActionPerformed(evt);
      }
    });

    buttonGroup1.add(ptn_Plus);
    ptn_Plus.setText("+");
    ptn_Plus.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ptn_PlusActionPerformed(evt);
      }
    });

    buttonGroup1.add(ptn_Multiply);
    ptn_Multiply.setText("*");
    ptn_Multiply.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ptn_MultiplyActionPerformed(evt);
      }
    });

    buttonGroup1.add(ptb_Subtract);
    ptb_Subtract.setText("-");
    ptb_Subtract.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ptb_SubtractActionPerformed(evt);
      }
    });

    buttonGroup1.add(ptn_Divide);
    ptn_Divide.setText("(A+B)/C");
    ptn_Divide.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ptn_DivideActionPerformed(evt);
      }
    });

    txt_Result.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txt_ResultActionPerformed(evt);
      }
    });

    jLabel7.setText("Kết quả");

    Combo_Box.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[] {"Chọn các hệ cơ số", "1", "2", "3", "4", "5", "6"}));
    Combo_Box.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Combo_BoxActionPerformed(evt);
      }
    });

    jLabel8.setText("CALCULATOR");

    lb_kitu.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        lb_kituActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout =
        new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup()
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addGroup(layout
                                                  .createParallelGroup(
                                                      javax.swing.GroupLayout
                                                          .Alignment.TRAILING)
                                                  .addComponent(jLabel4)
                                                  .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout
                                                  .createParallelGroup(
                                                      javax.swing.GroupLayout
                                                          .Alignment.LEADING,
                                                      false)
                                                  .addComponent(
                                                      value_X2,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      180, Short.MAX_VALUE)
                                                  .addComponent(value_x1)))
                            .addGroup(layout.createSequentialGroup()
                                          .addGap(75, 75, 75)
                                          .addComponent(Giai))
                            .addGroup(
                                layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout
                                                    .Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addGroup(
                                                layout
                                                    .createParallelGroup(
                                                        javax.swing.GroupLayout
                                                            .Alignment.LEADING,
                                                        false)
                                                    .addGroup(
                                                        layout
                                                            .createSequentialGroup()
                                                            .addComponent(
                                                                jLabel1)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(lb_A))
                                                    .addGroup(
                                                        layout
                                                            .createSequentialGroup()
                                                            .addComponent(
                                                                jLabel3)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(lb_c))
                                                    .addGroup(
                                                        layout
                                                            .createSequentialGroup()
                                                            .addComponent(
                                                                jLabel2,
                                                                javax.swing
                                                                    .GroupLayout
                                                                    .PREFERRED_SIZE,
                                                                8,
                                                                javax.swing
                                                                    .GroupLayout
                                                                    .PREFERRED_SIZE)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(
                                                                lb_b,
                                                                javax.swing
                                                                    .GroupLayout
                                                                    .PREFERRED_SIZE,
                                                                183,
                                                                javax.swing
                                                                    .GroupLayout
                                                                    .PREFERRED_SIZE))))))
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69,
                        Short.MAX_VALUE)
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout
                                                    .Alignment.TRAILING)
                                            .addComponent(ptn_Multiply)
                                            .addComponent(ptn_Divide)
                                            .addGroup(
                                                layout.createSequentialGroup()
                                                    .addComponent(
                                                        Combo_Box,
                                                        javax.swing.GroupLayout
                                                            .PREFERRED_SIZE,
                                                        133,
                                                        javax.swing.GroupLayout
                                                            .PREFERRED_SIZE)
                                                    .addGap(96, 96, 96)
                                                    .addGroup(
                                                        layout
                                                            .createParallelGroup(
                                                                javax.swing
                                                                    .GroupLayout
                                                                    .Alignment
                                                                    .LEADING)
                                                            .addComponent(
                                                                ptb_Subtract,
                                                                javax.swing
                                                                    .GroupLayout
                                                                    .Alignment
                                                                    .TRAILING)
                                                            .addComponent(
                                                                ptn_Plus,
                                                                javax.swing
                                                                    .GroupLayout
                                                                    .Alignment
                                                                    .TRAILING))))
                                    .addGap(167, 167, 167))
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(17, 17, 17)
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(
                                        lb_kitu,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        20,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(
                                        txt_Result,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        99,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(75, 75, 75))))
            .addGroup(
                layout.createSequentialGroup()
                    .addGroup(layout
                                  .createParallelGroup(
                                      javax.swing.GroupLayout.Alignment.LEADING)
                                  .addGroup(layout.createSequentialGroup()
                                                .addGap(367, 367, 367)
                                                .addComponent(jLabel10))
                                  .addGroup(layout.createSequentialGroup()
                                                .addGap(315, 315, 315)
                                                .addComponent(jLabel8)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                     Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout.createSequentialGroup()
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                          .addGap(32, 32, 32)
                                          .addComponent(ptn_Plus)
                                          .addGap(18, 18, 18)
                                          .addComponent(ptb_Subtract)
                                          .addGap(18, 18, 18)
                                          .addComponent(ptn_Multiply)
                                          .addGap(18, 18, 18)
                                          .addComponent(ptn_Divide))
                            .addGroup(
                                layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(25, 25, 25)
                                    .addGroup(layout
                                                  .createParallelGroup(
                                                      javax.swing.GroupLayout
                                                          .Alignment.BASELINE)
                                                  .addComponent(jLabel1)
                                                  .addComponent(
                                                      lb_A,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE)
                                                  .addComponent(
                                                      Combo_Box,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE))
                                    .addGap(9, 9, 9)
                                    .addGroup(layout
                                                  .createParallelGroup(
                                                      javax.swing.GroupLayout
                                                          .Alignment.BASELINE)
                                                  .addComponent(
                                                      lb_b,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE)
                                                  .addComponent(jLabel2))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout
                                                  .createParallelGroup(
                                                      javax.swing.GroupLayout
                                                          .Alignment.BASELINE)
                                                  .addComponent(
                                                      lb_c,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE)
                                                  .addComponent(jLabel3))
                                    .addGap(68, 68, 68)
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout
                                                  .createParallelGroup(
                                                      javax.swing.GroupLayout
                                                          .Alignment.BASELINE)
                                                  .addComponent(
                                                      value_x1,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE)
                                                  .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout
                                                  .createParallelGroup(
                                                      javax.swing.GroupLayout
                                                          .Alignment.BASELINE)
                                                  .addComponent(jLabel5)
                                                  .addComponent(
                                                      value_X2,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE)
                                                  .addComponent(
                                                      txt_Result,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE)
                                                  .addComponent(jLabel7)
                                                  .addComponent(jLabel9)
                                                  .addComponent(
                                                      lb_kitu,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE))
                                    .addGap(33, 33, 33)
                                    .addComponent(Giai)))
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72,
                        Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(40, 40, 40)));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void
  lb_kituActionPerformed(java.awt.event.ActionEvent
                             evt) { // GEN-FIRST:event_lb_kituActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_lb_kituActionPerformed

  private void ptb_SubtractActionPerformed(
      java.awt.event
          .ActionEvent evt) { // GEN-FIRST:event_ptb_SubtractActionPerformed
                              // TODO add your handling code here:
    String kitu = "-";
    lb_kitu.setText(kitu);
    Double a = Double.parseDouble(lb_A.getText());
    Double b = Double.parseDouble(lb_b.getText());
    Double c = Double.parseDouble(lb_c.getText());
    double result = a - b - c;
    txt_Result.setText(String.valueOf(result));

  } // GEN-LAST:event_ptb_SubtractActionPerformed

  private void ptn_MultiplyActionPerformed(
      java.awt.event
          .ActionEvent evt) { // GEN-FIRST:event_ptn_MultiplyActionPerformed
                              // TODO add your handling code here:
    String kitu = "*";
    lb_kitu.setText(kitu);
    Double a = Double.parseDouble(lb_A.getText());
    Double b = Double.parseDouble(lb_b.getText());
    Double c = Double.parseDouble(lb_c.getText());
    double result = a * b * c;
    txt_Result.setText(String.valueOf(result));
  } // GEN-LAST:event_ptn_MultiplyActionPerformed

  private void ptn_DivideActionPerformed(
      java.awt.event
          .ActionEvent evt) { // GEN-FIRST:event_ptn_DivideActionPerformed
                              // TODO add your handling code here:
    String kitu = ":";
    lb_kitu.setText(kitu);
    Double a = Double.parseDouble(lb_A.getText());
    Double b = Double.parseDouble(lb_b.getText());
    Double c = Double.parseDouble(lb_c.getText());
    double result = (a + b) / c;
    txt_Result.setText(String.valueOf(result));
  } // GEN-LAST:event_ptn_DivideActionPerformed

  private void Combo_BoxActionPerformed(
      java.awt.event
          .ActionEvent evt) { // GEN-FIRST:event_Combo_BoxActionPerformed
    // TODO add your handling code here:
    String T = Combo_Box.getSelectedItem().toString();
    double t = Double.parseDouble(T);
    lb_A.setText(T);
  } // GEN-LAST:event_Combo_BoxActionPerformed

  private void jTextField1ActionPerformed(
      java.awt.event
          .ActionEvent evt) { // GEN-FIRST:event_jTextField1ActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_jTextField1ActionPerformed

  private void lb_cActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_lb_cActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_lb_cActionPerformed

  private void
  ptn_PlusActionPerformed(java.awt.event.ActionEvent
                              evt) { // GEN-FIRST:event_ptn_PlusActionPerformed
                                     // TODO add your handling code here:
    String kitu = "+";
    lb_kitu.setText(kitu);
    Double a = Double.parseDouble(lb_A.getText());
    Double b = Double.parseDouble(lb_b.getText());
    Double c = Double.parseDouble(lb_c.getText());
    double result = a + b + c;
    txt_Result.setText(String.valueOf(result));
  } // GEN-LAST:event_ptn_PlusActionPerformed

  private void txt_ResultActionPerformed(
      java.awt.event
          .ActionEvent evt) { // GEN-FIRST:event_txt_ResultActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_txt_ResultActionPerformed

  private void GiaiActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_GiaiActionPerformed
    // TODO add your handling code here:
    Double a = Double.parseDouble(lb_A.getText());
    Double b = Double.parseDouble(lb_b.getText());
    Double c = Double.parseDouble(lb_c.getText());

    if (a == 0)
      JOptionPane.showMessageDialog(null, "ko phai pt b2, nghiem -b/c");
    else if (a > 0) {
      double delta = b * b - 4 * a * c;
      if (delta > 0) {
        double x1 = (-b + Math.sqrt(delta)) / (2 * a);
        double x2 = (-b - Math.sqrt(delta)) / (2 * a);
        value_x1.setText(String.valueOf(x1));
        value_X2.setText(String.valueOf(x2));
      } else if (delta == 0) {
        double x1 = -b / (2 * a);
        value_x1.setText(String.valueOf(x1));
        value_X2.setVisible(false);
        lb_b.setVisible(false);
      } else if (delta < 0) {
        JOptionPane.showMessageDialog(null, "PT vo nghiem");
      }
    }
  } // GEN-LAST:event_GiaiActionPerformed

  private void lb_AActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_lb_AActionPerformed
    // TODO add your handling code here:
    Combo_Box.getSelectedItem();

  } // GEN-LAST:event_lb_AActionPerformed

  private void
  value_x1ActionPerformed(java.awt.event.ActionEvent
                              evt) { // GEN-FIRST:event_value_x1ActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_value_x1ActionPerformed

  private void lb_bActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_lb_bActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_lb_bActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    //(optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the
     * default look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info :
           javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Demo.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Demo.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Demo.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Demo.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() { new Demo().setVisible(true); }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox<String> Combo_Box;
  private javax.swing.JButton Giai;
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JSpinner jSpinner1;
  private javax.swing.JTextField lb_A;
  private javax.swing.JTextField lb_b;
  private javax.swing.JTextField lb_c;
  private javax.swing.JTextField lb_kitu;
  private javax.swing.JRadioButton ptb_Subtract;
  private javax.swing.JRadioButton ptn_Divide;
  private javax.swing.JRadioButton ptn_Multiply;
  private javax.swing.JRadioButton ptn_Plus;
  private javax.swing.JTextField txt_Result;
  private javax.swing.JTextField value_X2;
  private javax.swing.JTextField value_x1;
  // End of variables declaration//GEN-END:variables
}
